version: "3"

services:
  transmission:
    image: haugene/transmission-openvpn
    restart: always
    ports:
      - "8080:9091"
      - "8888:8888"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    volumes:
      - ./torrents:/data
      - ./ovpn/auth.txt:/etc/openvpn/custom/auth.txt
      - ./ovpn/default.ovpn:/etc/openvpn/custom/default.ovpn
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000  # id -u $(whoami)
      - PGID=1000  # id -g $(whoami)
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - OPENVPN_USERNAME=dummy
      - OPENVPN_PASSWORD=dummy
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - LOCAL_NETWORK=10.8.2.0/24
      - OPENVPN_PROVIDER=CUSTOM

