version: "3"

services:
  transmission:
    image: haugene/transmission-openvpn
    restart: always
    ports:
     - "8080:9091"
     - "8888:8888"
    dns:
    - "8.8.8.8"
    - "8.8.4.4"
    volumes:
     - ./data:/data
     - ../ovpn/const.ovpn:/etc/openvpn/custom/default.ovpn
     - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun
    cap_add:
     - NET_ADMIN
    env_file:
      - ../ovpn/secrets.env
    environment:
      # User ID: id -u $(whoami)
      - PUID=1000
      # Group ID: id -g $(whoami)
      - PGID=1000
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --auth-nocache --mute-replay-warnings
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - LOCAL_NETWORK=10.8.2.0/24
      - OPENVPN_PROVIDER=CUSTOM

